apiVersion: v1
kind: ConfigMap
metadata:
  name: finpay-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv }}
  LOG_LEVEL: {{ .Values.config.logLevel }}
  DB_URL: {{ .Values.config.dbUrl }}
