apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: payment-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/database/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/database/credentials
        property: password