apiVersion: v1
kind: Secret
metadata:
  name: finpay-db-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}
