# secrets: AWS_ACCOUNT_ID, AWS_ROLE_ARN_ECR_PUSH

name: CI (AWS ECR)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com
  PROJECT_NAME: finpay

jobs:



  build-payment-api:
    name: Build & Scan payment-api
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build payment-api image
        uses: docker/build-push-action@v5
        with:
          context: ./app/payment-api
          file: ./app/payment-api/Dockerfile
          push: false
          load: true
          tags: payment-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: payment-api:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Run Trivy scanner (SARIF report)
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: payment-api:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-api-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-api-results.sarif'

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_ECR_PUSH }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push payment-api to ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./app/payment-api
          file: ./app/payment-api/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.PROJECT_NAME }}/payment-api:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/${{ env.PROJECT_NAME }}/payment-api:main-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max





  build-payment-worker:
    name: Build & Scan payment-worker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build payment-worker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/payment-worker
          file: ./app/payment-worker/Dockerfile
          push: false
          load: true
          tags: payment-worker:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: payment-worker:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Run Trivy scanner (SARIF report)
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: payment-worker:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-worker-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-worker-results.sarif'

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_ECR_PUSH }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push payment-worker to ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./app/payment-worker
          file: ./app/payment-worker/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.PROJECT_NAME }}/payment-worker:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/${{ env.PROJECT_NAME }}/payment-worker:main-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
